name: CELPIP Checker

on:
  schedule:
    - cron: '0 8-23 * * *'    # 每小时整点
    - cron: '10 8-23 * * *'   # 每小时第10分钟
    - cron: '20 8-23 * * *'   # 每小时第20分钟
    - cron: '30 8-23 * * *'   # 每小时第30分钟
    - cron: '40 8-23 * * *'   # 每小时第40分钟
    - cron: '50 8-23 * * *'   # 每小时第50分钟
  workflow_dispatch:  # 允许手动触发

jobs:
  check-celpip:
    runs-on: ubuntu-latest
    container:
      image: selenium/standalone-edge:latest
      options: --shm-size="2g"
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Cache Python packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Add Gmail credentials
      run: |
        echo "e_user=${{ secrets.EMAIL_USER }}" >> $GITHUB_ENV
        echo "e_pwd=${{ secrets.EMAIL_PASSWORD }}" >> $GITHUB_ENV
        echo "e_client=${{ secrets.EMAIL_CLIENT }}" >> $GITHUB_ENV
    
    - name: Run script
      run: |
        # Run the Python script
        python celpip.py